=== laurentkeil/lil-g3r/HLB-DC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers" xmlns:dc="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers" elementFormDefault="qualified">

   <complexType name="centersType">
    	<sequence>
    		<element name="center" type="dc:centerType"></element>
    	</sequence>
    </complexType>

    <complexType name="centerType">
    	<sequence>
            <element name="employees" type="dc:employeesType"></element>
            <element name="trolleys" type="dc:trolleysType"></element>
    		<element name="vehicles" type="dc:vehiclesType"></element>
    	</sequence>
    	<attribute name="name">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="Liège"></enumeration>
    				<enumeration value="Hasselt"></enumeration>
    				<enumeration value="Arlon"></enumeration>
    				<enumeration value="Namur"></enumeration>
    				<enumeration value="Mons"></enumeration>
    				<enumeration value="Wavre"></enumeration>
    				<enumeration value="Louvain"></enumeration>
    				<enumeration value="Gand"></enumeration>
    				<enumeration value="Anvers"></enumeration>
    				<enumeration value="Bruges"></enumeration>
    				<enumeration value="Aéroport-Bruxelles"></enumeration>
    				<enumeration value="Aéroport-Liège"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="employeeType">
    	<sequence>
    		<element name="homeaddress" type="dc:addressType"></element>
    		<element name="role">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="préposé"></enumeration>
    					<enumeration value="coursier"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="unavailabilities" type="dc:unavailabilitiesType" minOccurs="0"></element>
    	</sequence>
    	<attribute name="idemployee" type="string" use="required"></attribute>
        <attribute name="firstname" type="string" use="required"></attribute>
    	<attribute name="lastname" type="string" use="required"></attribute>
    	<attribute name="birthdate" type="string" use="required"></attribute>
    	<attribute name="phone" type="string" use="required"></attribute>
    </complexType>

    <complexType name="addressType">
    	<attribute name="street" type="string" use="required"></attribute>
    	<attribute name="number" type="string" use="required"></attribute>
    	<attribute name="box" type="string" use="optional"></attribute>
    	<attribute name="city" type="string" use="required"></attribute>
    	<attribute name="zip" type="string" use="required"></attribute>
    	<attribute name="country" type="string" use="required"></attribute>
    </complexType>

    <complexType name="trolleyType">
    	<sequence>
    		<element name="dimension" type="dc:dimension"></element>
    	</sequence>
    	<attribute name="status">
            <annotation>
            	<documentation>Statut du chariot au niveau du centre de dispatching : empty (vide), ready-deliver(contient colis à liver dans le même canton), incoming(contient colis provenant de l'extérieur du pays), outgoing (contient colis en partance à l'extérieur du pays)</documentation>
            </annotation>
            <simpleType>
    			<restriction base="string">
    				<enumeration value="empty"></enumeration>
    				<enumeration value="ready-deliver"></enumeration>
    				<enumeration value="incoming"></enumeration>
    				<enumeration value="outgoing"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="vehicleType">
    	<annotation>
    		<documentation></documentation>
    	</annotation>
    	<sequence>
    		<element name="dimension" type="dc:dimension"></element>
    		<element name="employeeincharge" type="string"></element>
    	</sequence>
        <attribute name="model" type="string"></attribute>
        <attribute name="usefulweight" type="float"></attribute>
        <attribute name="passengernumber" type="int"></attribute>
    </complexType>

    <complexType name="unavailabilityType">
    	<attribute name="from" type="dateTime" use="required"></attribute>
    	<attribute name="to" type="dateTime" use="required"></attribute>
    	<attribute name="reason" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="congé"></enumeration>
    				<enumeration value="panne"></enumeration>
    				<enumeration value="ciruclation"></enumeration>
    				<enumeration value="assigné"></enumeration>
    				<enumeration value="autres"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="assignedcenter" use="optional">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="Liège"></enumeration>
    				<enumeration value="Hasselt"></enumeration>
    				<enumeration value="Arlon"></enumeration>
    				<enumeration value="Namur"></enumeration>
    				<enumeration value="Mons"></enumeration>
    				<enumeration value="Wavre"></enumeration>
    				<enumeration value="Louvain"></enumeration>
    				<enumeration value="Gand"></enumeration>
    				<enumeration value="Avers"></enumeration>
    				<enumeration value="Bruges"></enumeration>
    				<enumeration value="Aéroport-Liège"></enumeration>
    				<enumeration value="Aéroport-Bruxelles"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="dimension">
    	<attribute name="volume" type="float" use="required">
    		<annotation>
    			<documentation>Volume en m^3</documentation>
    		</annotation></attribute>
    	<attribute name="usefullength" type="float" use="required">
    		<annotation>
    			<documentation>Longueur utile en m</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="usefulwidth" type="float" use="required">
    		<annotation>
    			<documentation>largeur utile en m</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="usefulheight" type="float" use="required">
    		<annotation>
    			<documentation>hauteur utile en m</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="totalheight" type="float" use="optional">
    		<annotation>
    			<documentation>hauteur totale en m</documentation>
    		</annotation>
    	</attribute>
    </complexType>


    <element name="centers" type="dc:centersType"></element>

    <complexType name="unavailabilitiesType">
    	<sequence>
    		<element name="unavailability" type="dc:unavailabilityType" minOccurs="1" maxOccurs="5"></element>
    	</sequence>
    </complexType>

    <complexType name="trolleysType">
    	<sequence>
    		<element name="trolley" type="dc:trolleyType" minOccurs="1" maxOccurs="20"></element>
    	</sequence>
    </complexType>

    <complexType name="vehiclesType">
    	<sequence>
    		<element name="vehicle" type="dc:vehicleType" minOccurs="1" maxOccurs="20"></element>
    	</sequence>
    </complexType>

    <complexType name="employeesType">
    	<sequence>
    		<element name="employee" type="dc:employeeType" minOccurs="1" maxOccurs="20"></element>
    	</sequence>
    </complexType>
</schema>

=== laurentkeil/lil-g3r/dispatching-centers.xml
<?xml version="1.0" encoding="UTF-8"?>
<dc:centers
	xmlns:dc="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers HLB-DC.xsd ">
	<dc:center name="Liège">
	
		<!-- Employés du centre -->
		<dc:employees>
			<dc:employee birthdate="12/12/1984" firstname="Jean-baptiste"
				lastname="Jaillet" idemployee="jjeanbaptiste" phone="0485859811">
				<dc:homeaddress box="5" city="Liège" country="Belgique"
					number="20" street="Rue Libotte" zip="4000" />
				<dc:role>coursier</dc:role>
				<dc:unavailabilities>
					<dc:unavailability from="2014-01-14T14:00:00" to="2014-01-14T14:30:00"
						reason="assigné" assignedcenter="Namur" />
					<dc:unavailability from="2014-07-15T18:00:00" to="2014-07-30T18:00:00"
						reason="congé" />
				</dc:unavailabilities>
			</dc:employee>
			
			<dc:employee birthdate="12/12/1984" firstname="Nathalie"
				lastname="Darc" idemployee="ndarc" phone="0485859815">
				<dc:homeaddress box="15" city="Liège" country="Belgique"
					number="20" street="Rue du marché" zip="4000" />
				<dc:role>coursier</dc:role>
				<dc:unavailabilities>
					<dc:unavailability from="2014-08-02T18:00:00" to="2014-07-30T18:00:00"
						reason="congé" />
				</dc:unavailabilities>
			</dc:employee>
			
		</dc:employees>
		
		<!-- Chariots du centre -->
		<dc:trolleys>
			<dc:trolley status="empty">
				<dc:dimension usefulheight="0.95" usefullength="1.2" usefulwidth="0.5" volume="0.057" />
			</dc:trolley>
			<dc:trolley status="ready-deliver">
				<dc:dimension usefulheight="0.95" usefullength="1.2" usefulwidth="0.5" volume="0.057" />
			</dc:trolley>
		</dc:trolleys>
		
		<!-- Véhicules du centre -->
		<dc:vehicles>
			<dc:vehicle model="renault-trafic-n34" passengernumber="3" usefulweight="896">
				<dc:dimension totalheight="1.90" usefulheight="1.26"
					usefullength="1.65" usefulwidth="1.65" volume="5" />
				<dc:employeeincharge>ndarc</dc:employeeincharge>
			</dc:vehicle>
			
			<dc:vehicle model="renault-trafic-n14" passengernumber="3" usefulweight="1000">
				<dc:dimension totalheight="2.33" usefulheight="1.76"
					usefullength="2.60" usefulwidth="1.60" volume="5" />
				<dc:employeeincharge>ndarc</dc:employeeincharge>
			</dc:vehicle>
		</dc:vehicles>
	</dc:center>
</dc:centers>

=== laurentkeil/lil-g3r/DC4.xml
<?xml version="1.0" encoding="UTF-8"?>
<centers xmlns="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers ../HLB-DC.xsd ">
	<center name="Namur">
		<employees>
			<employee birthdate="1959-03-28" firstname="Soren" lastname="Blokzijl"
				idemployee="s.blokzijl" phone="950336650">
				<homeaddress box="" city="Saint-Marc" country="Belgium"
					zip="5003" number="205" street="Rue de la Hulotais" />
				<role>préposé</role>
			</employee>
			<employee birthdate="1986-07-14" firstname="Stéphanie"
				lastname="Aartman" idemployee="s.aartman" phone="437132905">
				<homeaddress box="" city="Binche" country="Belgium" zip="7130"
					number="162" street="Rue de Strasbourg" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-06-17T04:24:16" to="2014-12-31T08:57:35"
						reason="autres" />
					<unavailability from="2014-02-18T11:45:38" to="2014-02-18T12:50:46"
						reason="ciruclation" />
					<unavailability from="2014-12-16T23:40:14" to="2015-06-26T13:30:40"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1948-12-04" firstname="Archaimbau"
				lastname="Mainville" idemployee="a.mainville" phone="186760504">
				<homeaddress box="" city="Maurage" country="Belgium"
					zip="7110" number="103" street="Rue de la Mare aux Carats" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T12:23:18" to="2014-02-18T13:45:03"
						reason="ciruclation" />
				</unavailabilities>
			</employee>
			<employee birthdate="1938-12-29" firstname="Jane" lastname="Bordeaux"
				idemployee="j.bordeaux" phone="6913858">
				<homeaddress box="C" city="Rochehaut" country="Belgium"
					zip="6830" number="70" street="Chemin Des Bateliers" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-22T22:41:02" to="2014-02-23T14:05:59"
						reason="assigné" assignedcenter="Namur" />
					<unavailability from="2014-09-27T02:45:50" to="2014-12-14T23:32:33"
						reason="autres" />
					<unavailability from="2014-08-01T08:03:18" to="2014-09-11T23:42:10"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1943-12-27" firstname="Maximilian"
				lastname="Pouchard" idemployee="m.pouchard" phone="916509986">
				<homeaddress box="" city="Nevele" country="Belgium" zip="9850"
					number="187" street="Vleugelboot" />
				<role>coursier</role>
			</employee>
			<employee birthdate="1942-01-30" firstname="Bouwina"
				lastname="Hulleman" idemployee="b.hulleman" phone="685603072">
				<homeaddress box="A" city="Seraing" country="Belgium"
					zip="4100" number="89" street="Avenue Millies Lacroix" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-24T13:24:03" to="2014-02-26T16:52:04"
						reason="assigné" assignedcenter="Namur" />
				</unavailabilities>
			</employee>
			<employee birthdate="1909-05-12" firstname="Sven" lastname="Weijman"
				idemployee="s.weijman" phone="592297630">
				<homeaddress box="E" city="Gesves" country="Belgium"
					zip="5340" number="187" street="Rue du Général Ailleret" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-10-16T22:33:00" to="2015-01-11T10:57:06"
						reason="autres" />
				</unavailabilities>
			</employee>
			<employee birthdate="1909-06-20" firstname="David" lastname="Bril"
				idemployee="d.bril" phone="833324491">
				<homeaddress box="A" city="Sart-Saint-Laurent" country="Belgium"
					zip="5070" number="181" street="Rue Michel Ange" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T11:50:44" to="2014-02-18T12:04:10"
						reason="ciruclation" />
					<unavailability from="2014-11-09T14:51:39" to="2014-11-11T20:17:16"
						reason="autres" />
					<unavailability from="2014-11-24T18:56:36" to="2014-12-06T08:31:58"
						reason="autres" />
				</unavailabilities>
			</employee>
		</employees>
		<trolleys>
			<trolley status="ready-deliver">
				<dimension totalheight="0.59839314" usefulheight="0.49866095"
					usefullength="1.5285515" usefulwidth="1.2932314" volume="0.98573834" />
			</trolley>
			<trolley status="empty">
				<dimension totalheight="1.0652537" usefulheight="0.88771147"
					usefullength="1.5399952" usefulwidth="1.1152517" volume="1.5246286" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="0.771537" usefulheight="0.6429475"
					usefullength="1.7779176" usefulwidth="1.6134905" volume="1.8443933" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="1.3089006" usefulheight="1.0907505"
					usefullength="1.8651612" usefulwidth="0.88951457" volume="1.8096511" />
			</trolley>
			<trolley status="ready-deliver">
				<dimension totalheight="0.8076433" usefulheight="0.6730361"
					usefullength="1.4118285" usefulwidth="0.8960113" volume="0.8514003" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="0.5748053" usefulheight="0.47900444"
					usefullength="2.001648" usefulwidth="0.82118785" volume="0.7873535" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="0.7279702" usefulheight="0.6066418"
					usefullength="1.3219512" usefulwidth="1.1160431" volume="0.8950117" />
			</trolley>
			<trolley status="empty">
				<dimension totalheight="0.9266727" usefulheight="0.7722272"
					usefullength="1.2363828" usefulwidth="1.2339976" volume="1.178182" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="0.8838856" usefulheight="0.7365714"
					usefullength="1.8562223" usefulwidth="1.372009" volume="1.8758659" />
			</trolley>
		</trolleys>
		<vehicles>
			<vehicle model="renault-trafic-n14" passengernumber="1"
				usefulweight="837.43567">
				<dimension totalheight="1.8184814" usefulheight="1.5154012"
					usefullength="2.0523682" usefulwidth="1.3209904" volume="4.1084933" />
				<employeeincharge>s.blokzijl</employeeincharge>
			</vehicle>
			<vehicle model="Ford transit" passengernumber="2"
				usefulweight="844.0333">
				<dimension totalheight="1.906753" usefulheight="1.5889608"
					usefullength="2.1028843" usefulwidth="1.4498372" volume="4.8444867" />
				<employeeincharge>s.aartman</employeeincharge>
			</vehicle>
			<vehicle model="Renault Master" passengernumber="1"
				usefulweight="1034.3687">
				<dimension totalheight="2.1963491" usefulheight="1.8302909"
					usefullength="2.4378357" usefulwidth="1.8459402" volume="8.23649" />
				<employeeincharge>a.mainville</employeeincharge>
			</vehicle>
			<vehicle model="Citroën Nemo" passengernumber="2"
				usefulweight="648.87396">
				<dimension totalheight="2.2357059" usefulheight="1.8630883"
					usefullength="1.9345669" usefulwidth="1.294033" volume="4.664043" />
				<employeeincharge>j.bordeaux</employeeincharge>
			</vehicle>
			<vehicle model="Ford transit" passengernumber="1"
				usefulweight="724.216">
				<dimension totalheight="1.8724126" usefulheight="1.5603437"
					usefullength="1.9906994" usefulwidth="1.1863228" volume="3.6849267" />
				<employeeincharge>m.pouchard</employeeincharge>
			</vehicle>
			<vehicle model="Ford transit" passengernumber="2"
				usefulweight="431.6723">
				<dimension totalheight="1.582777" usefulheight="1.3189808"
					usefullength="2.4121022" usefulwidth="1.5235267" volume="4.8471255" />
				<employeeincharge>b.hulleman</employeeincharge>
			</vehicle>
			<vehicle model="Renault Master" passengernumber="1"
				usefulweight="538.40076">
				<dimension totalheight="1.557632" usefulheight="1.2980267"
					usefullength="2.2514238" usefulwidth="1.7967858" volume="5.2509413" />
				<employeeincharge>s.weijman</employeeincharge>
			</vehicle>
			<vehicle model="Ford transit" passengernumber="2"
				usefulweight="923.76514">
				<dimension totalheight="1.7326269" usefulheight="1.4438558"
					usefullength="2.0677636" usefulwidth="1.7901495" volume="5.344585" />
				<employeeincharge>d.bril</employeeincharge>
			</vehicle>
		</vehicles>
	</center>
</centers>

=== laurentkeil/lil-g3r/DC10.xml
<?xml version="1.0" encoding="UTF-8"?>
<centers xmlns="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers ../HLB-DC.xsd ">
	<center name="Bruges">
		<employees>
			<employee birthdate="1973-01-26" firstname="Pansy" lastname="Guibord"
				idemployee="p.guibord" phone="1359054991">
				<homeaddress box="" city="Tongres" country="Belgium"
					zip="3700" number="169" street="Prunuslaan" />
				<role>préposé</role>
				<unavailabilities>
					<unavailability from="2014-02-18T11:29:53" to="2014-02-18T13:25:48"
						reason="ciruclation" />
					<unavailability from="2014-02-18T08:23:32" to="2014-02-18T17:42:20"
						reason="panne" />
					<unavailability from="2015-01-17T06:07:45" to="2015-08-11T15:53:01"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1978-07-07" firstname="Dixie" lastname="Étoile"
				idemployee="d.etoile" phone="1316451351">
				<homeaddress box="E" city="Esneux" country="Belgium"
					zip="4130" number="162" street="Avenue de l'Amandier" />
				<role>coursier</role>
			</employee>
			<employee birthdate="1941-05-28" firstname="Soulaimane"
				lastname="Denis" idemployee="s.denis" phone="1811609323">
				<homeaddress box="" city="Assent" country="Belgium" zip="3460"
					number="154" street="BurgemeesterBrandtlaan" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T11:38:18" to="2014-02-18T11:58:56"
						reason="ciruclation" />
					<unavailability from="2014-02-18T14:34:44" to="2014-02-18T17:25:50"
						reason="panne" />
					<unavailability from="2014-02-18T12:04:35" to="2014-02-18T12:33:18"
						reason="ciruclation" />
				</unavailabilities>
			</employee>
			<employee birthdate="1905-02-27" firstname="Manuela"
				lastname="Alblas" idemployee="m.alblas" phone="680228735">
				<homeaddress box="" city="Vlissegem" country="Belgium"
					zip="8421" number="143" street="Laurentiusstraat" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-22T22:21:02" to="2014-03-01T13:23:38"
						reason="assigné" assignedcenter="Bruges" />
					<unavailability from="2014-03-08T18:07:59" to="2014-08-26T00:24:39"
						reason="autres" />
				</unavailabilities>
			</employee>
			<employee birthdate="1986-02-12" firstname="Danée" lastname="Baron"
				idemployee="d.baron" phone="17011836">
				<homeaddress box="C" city="Mont-Sainte-Geneviève"
					country="Belgium" zip="6540" number="44" street="Avenue Jean Portalis" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T13:33:19" to="2014-02-18T15:03:28"
						reason="panne" />
				</unavailabilities>
			</employee>
			<employee birthdate="1983-03-20" firstname="Peterke"
				lastname="Steijns" idemployee="p.steijns" phone="1143185057">
				<homeaddress box="" city="Bonsin" country="Belgium" zip="5377"
					number="111" street="Rue Léon Dierx" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T11:41:58" to="2014-02-18T13:58:15"
						reason="panne" />
					<unavailability from="2014-02-19T13:46:48" to="2014-08-02T03:01:56"
						reason="autres" />
				</unavailabilities>
			</employee>
			<employee birthdate="1980-10-21" firstname="Telford"
				lastname="Hartemink" idemployee="t.hartemink" phone="250106691">
				<homeaddress box="C" city="Mont" country="Belgium" zip="6661"
					number="4" street="Place Maurice-Charretier" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-24T03:44:53" to="2014-02-26T08:25:26"
						reason="assigné" assignedcenter="Bruges" />
					<unavailability from="2014-02-18T10:28:47" to="2014-02-18T12:36:51"
						reason="panne" />
				</unavailabilities>
			</employee>
			<employee birthdate="1920-09-16" firstname="Anne" lastname="Allain"
				idemployee="a.allain" phone="1324874752">
				<homeaddress box="D" city="Kermt" country="Belgium" zip="3510"
					number="78" street="Wesselsstraat" />
				<role>coursier</role>
			</employee>
			<employee birthdate="1925-01-08" firstname="Geneviève"
				lastname="Hulleman" idemployee="g.hulleman" phone="1098225625">
				<homeaddress box="" city="Alost" country="Belgium" zip="9300"
					number="97" street="Azaleastraat" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T14:40:32" to="2014-02-18T15:31:23"
						reason="panne" />
					<unavailability from="2014-02-18T12:33:36" to="2014-02-18T16:58:16"
						reason="panne" />
					<unavailability from="2014-06-02T19:47:58" to="2014-10-10T13:42:11"
						reason="autres" />
				</unavailabilities>
			</employee>
		</employees>
		<trolleys>
			<trolley status="ready-deliver">
				<dimension totalheight="0.70632195" usefulheight="0.58860165"
					usefullength="1.5890555" usefulwidth="1.2607315" volume="1.1791883" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="0.7870815" usefulheight="0.65590125"
					usefullength="1.3735937" usefulwidth="1.1714063" volume="1.0553689" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="0.8420792" usefulheight="0.7017327"
					usefullength="2.0930629" usefulwidth="1.5421259" volume="2.2650292" />
			</trolley>
			<trolley status="ready-deliver">
				<dimension totalheight="1.2585497" usefulheight="1.0487914"
					usefullength="1.7700033" usefulwidth="1.5382603" volume="2.8555715" />
			</trolley>
			<trolley status="ready-deliver">
				<dimension totalheight="1.2338355" usefulheight="1.0281962"
					usefullength="1.9591" usefulwidth="1.6336926" volume="3.290811" />
			</trolley>
			<trolley status="empty">
				<dimension totalheight="0.7921948" usefulheight="0.6601623"
					usefullength="1.2511135" usefulwidth="1.3705597" volume="1.1319973" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="1.0073397" usefulheight="0.83944976"
					usefullength="1.5648079" usefulwidth="1.358924" volume="1.7850522" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="1.3600042" usefulheight="1.1333368"
					usefullength="2.1180618" usefulwidth="1.5997915" volume="3.8402634" />
			</trolley>
			<trolley status="ready-deliver">
				<dimension totalheight="1.0322363" usefulheight="0.86019695"
					usefullength="1.6521603" usefulwidth="1.1463983" volume="1.6292421" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="1.4065578" usefulheight="1.1721315"
					usefullength="1.8868277" usefulwidth="1.2072394" volume="2.669943" />
			</trolley>
		</trolleys>
		<vehicles>
			<vehicle model="Opel vivano" passengernumber="2"
				usefulweight="472.3225">
				<dimension totalheight="2.1244986" usefulheight="1.7704155"
					usefullength="2.0494757" usefulwidth="1.7791717" volume="6.455589" />
				<employeeincharge>p.guibord</employeeincharge>
			</vehicle>
			<vehicle model="Citroën Nemo" passengernumber="1"
				usefulweight="408.8034">
				<dimension totalheight="1.6487502" usefulheight="1.3739585"
					usefullength="2.8630128" usefulwidth="1.1876949" volume="4.671989" />
				<employeeincharge>d.etoile</employeeincharge>
			</vehicle>
			<vehicle model="Opel vivano" passengernumber="1"
				usefulweight="957.193">
				<dimension totalheight="2.3163261" usefulheight="1.9302717"
					usefullength="2.4808102" usefulwidth="1.6489768" volume="7.8963523" />
				<employeeincharge>s.denis</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n34" passengernumber="2"
				usefulweight="882.77466">
				<dimension totalheight="2.4609597" usefulheight="2.0507998"
					usefullength="2.848141" usefulwidth="1.9287649" volume="11.265853" />
				<employeeincharge>m.alblas</employeeincharge>
			</vehicle>
			<vehicle model="Opel Movano" passengernumber="1"
				usefulweight="905.6531">
				<dimension totalheight="1.8371019" usefulheight="1.5309182"
					usefullength="2.8865242" usefulwidth="1.4493886" volume="6.4048953" />
				<employeeincharge>d.baron</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n34" passengernumber="1"
				usefulweight="1075.4026">
				<dimension totalheight="2.0154705" usefulheight="1.6795588"
					usefullength="2.2710574" usefulwidth="1.2462876" volume="4.753807" />
				<employeeincharge>p.steijns</employeeincharge>
			</vehicle>
			<vehicle model="Renault Master" passengernumber="1"
				usefulweight="627.1965">
				<dimension totalheight="2.0230043" usefulheight="1.6858369"
					usefullength="2.2851286" usefulwidth="1.8375573" volume="7.0789213" />
				<employeeincharge>t.hartemink</employeeincharge>
			</vehicle>
			<vehicle model="Opel vivano" passengernumber="2"
				usefulweight="572.30414">
				<dimension totalheight="1.9146332" usefulheight="1.5955276"
					usefullength="2.5907357" usefulwidth="1.3018942" volume="5.381497" />
				<employeeincharge>a.allain</employeeincharge>
			</vehicle>
			<vehicle model="Renault Master" passengernumber="2"
				usefulweight="667.1421">
				<dimension totalheight="1.7699356" usefulheight="1.4749464"
					usefullength="2.5342245" usefulwidth="1.4794103" volume="5.5298066" />
				<employeeincharge>g.hulleman</employeeincharge>
			</vehicle>
		</vehicles>
	</center>
</centers>
