=== laurentkeil/lil-g3r/HLB-DC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers" xmlns:dc="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers" elementFormDefault="qualified">

   <complexType name="centersType">
    	<sequence>
    		<element name="center" type="dc:centerType"></element>
    	</sequence>
    </complexType>

    <complexType name="centerType">
    	<sequence>
            <element name="employees" type="dc:employeesType"></element>
            <element name="trolleys" type="dc:trolleysType"></element>
    		<element name="vehicles" type="dc:vehiclesType"></element>
    	</sequence>
    	<attribute name="name">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="Liège"></enumeration>
    				<enumeration value="Hasselt"></enumeration>
    				<enumeration value="Arlon"></enumeration>
    				<enumeration value="Namur"></enumeration>
    				<enumeration value="Mons"></enumeration>
    				<enumeration value="Wavre"></enumeration>
    				<enumeration value="Louvain"></enumeration>
    				<enumeration value="Gand"></enumeration>
    				<enumeration value="Anvers"></enumeration>
    				<enumeration value="Bruges"></enumeration>
    				<enumeration value="Aéroport-Bruxelles"></enumeration>
    				<enumeration value="Aéroport-Liège"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="employeeType">
    	<sequence>
    		<element name="homeaddress" type="dc:addressType"></element>
    		<element name="role">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="préposé"></enumeration>
    					<enumeration value="coursier"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="unavailabilities" type="dc:unavailabilitiesType" minOccurs="0"></element>
    	</sequence>
    	<attribute name="idemployee" type="string" use="required"></attribute>
        <attribute name="firstname" type="string" use="required"></attribute>
    	<attribute name="lastname" type="string" use="required"></attribute>
    	<attribute name="birthdate" type="string" use="required"></attribute>
    	<attribute name="phone" type="string" use="required"></attribute>
    </complexType>

    <complexType name="addressType">
    	<attribute name="street" type="string" use="required"></attribute>
    	<attribute name="number" type="string" use="required"></attribute>
    	<attribute name="box" type="string" use="optional"></attribute>
    	<attribute name="city" type="string" use="required"></attribute>
    	<attribute name="zip" type="string" use="required"></attribute>
    	<attribute name="country" type="string" use="required"></attribute>
    </complexType>

    <complexType name="trolleyType">
    	<sequence>
    		<element name="dimension" type="dc:dimension"></element>
    	</sequence>
    	<attribute name="status">
            <annotation>
            	<documentation>Statut du chariot au niveau du centre de dispatching : empty (vide), ready-deliver(contient colis à liver dans le même canton), incoming(contient colis provenant de l'extérieur du pays), outgoing (contient colis en partance à l'extérieur du pays)</documentation>
            </annotation>
            <simpleType>
    			<restriction base="string">
    				<enumeration value="empty"></enumeration>
    				<enumeration value="ready-deliver"></enumeration>
    				<enumeration value="incoming"></enumeration>
    				<enumeration value="outgoing"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="vehicleType">
    	<annotation>
    		<documentation></documentation>
    	</annotation>
    	<sequence>
    		<element name="dimension" type="dc:dimension"></element>
    		<element name="employeeincharge" type="string"></element>
    	</sequence>
        <attribute name="model" type="string"></attribute>
        <attribute name="usefulweight" type="float"></attribute>
        <attribute name="passengernumber" type="int"></attribute>
    </complexType>

    <complexType name="unavailabilityType">
    	<attribute name="from" type="dateTime" use="required"></attribute>
    	<attribute name="to" type="dateTime" use="required"></attribute>
    	<attribute name="reason" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="congé"></enumeration>
    				<enumeration value="panne"></enumeration>
    				<enumeration value="ciruclation"></enumeration>
    				<enumeration value="assigné"></enumeration>
    				<enumeration value="autres"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="assignedcenter" use="optional">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="Liège"></enumeration>
    				<enumeration value="Hasselt"></enumeration>
    				<enumeration value="Arlon"></enumeration>
    				<enumeration value="Namur"></enumeration>
    				<enumeration value="Mons"></enumeration>
    				<enumeration value="Wavre"></enumeration>
    				<enumeration value="Louvain"></enumeration>
    				<enumeration value="Gand"></enumeration>
    				<enumeration value="Avers"></enumeration>
    				<enumeration value="Bruges"></enumeration>
    				<enumeration value="Aéroport-Liège"></enumeration>
    				<enumeration value="Aéroport-Bruxelles"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="dimension">
    	<attribute name="volume" type="float" use="required">
    		<annotation>
    			<documentation>Volume en m^3</documentation>
    		</annotation></attribute>
    	<attribute name="usefullength" type="float" use="required">
    		<annotation>
    			<documentation>Longueur utile en m</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="usefulwidth" type="float" use="required">
    		<annotation>
    			<documentation>largeur utile en m</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="usefulheight" type="float" use="required">
    		<annotation>
    			<documentation>hauteur utile en m</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="totalheight" type="float" use="optional">
    		<annotation>
    			<documentation>hauteur totale en m</documentation>
    		</annotation>
    	</attribute>
    </complexType>


    <element name="centers" type="dc:centersType"></element>

    <complexType name="unavailabilitiesType">
    	<sequence>
    		<element name="unavailability" type="dc:unavailabilityType" minOccurs="1" maxOccurs="5"></element>
    	</sequence>
    </complexType>

    <complexType name="trolleysType">
    	<sequence>
    		<element name="trolley" type="dc:trolleyType" minOccurs="1" maxOccurs="20"></element>
    	</sequence>
    </complexType>

    <complexType name="vehiclesType">
    	<sequence>
    		<element name="vehicle" type="dc:vehicleType" minOccurs="1" maxOccurs="20"></element>
    	</sequence>
    </complexType>

    <complexType name="employeesType">
    	<sequence>
    		<element name="employee" type="dc:employeeType" minOccurs="1" maxOccurs="20"></element>
    	</sequence>
    </complexType>
</schema>

=== laurentkeil/lil-g3r/DC5.xml
<?xml version="1.0" encoding="UTF-8"?>
<centers xmlns="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers ../HLB-DC.xsd ">
	<center name="Mons">
		<employees>
			<employee birthdate="1971-01-22" firstname="Kian" lastname="Bisaillon"
				idemployee="k.bisaillon" phone="1042968945">
				<homeaddress box="" city="Libramont" country="Belgium"
					zip="6800" number="204" street="Rue St Ferréol" />
				<role>préposé</role>
			</employee>
			<employee birthdate="1925-09-14" firstname="Maysa" lastname="Desnoyer"
				idemployee="m.desnoyer" phone="883436811">
				<homeaddress box="C" city="Tintigny" country="Belgium"
					zip="6730" number="29" street="Boulevard Aristide Briand" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-08-08T12:44:02" to="2014-10-11T10:05:10"
						reason="congé" />
					<unavailability from="2014-02-18T10:21:38" to="2014-02-18T15:24:15"
						reason="panne" />
					<unavailability from="2014-02-18T13:31:02" to="2014-02-18T13:36:50"
						reason="ciruclation" />
				</unavailabilities>
			</employee>
			<employee birthdate="1990-09-17" firstname="Millicent"
				lastname="Salmons" idemployee="m.salmons" phone="907708724">
				<homeaddress box="E" city="Weillen" country="Belgium"
					zip="5523" number="204" street="Boulevard de Normandie" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-10-04T03:38:07" to="2014-11-10T23:54:05"
						reason="congé" />
					<unavailability from="2014-02-18T12:03:49" to="2014-02-18T17:03:57"
						reason="panne" />
					<unavailability from="2014-08-01T20:16:29" to="2015-02-21T06:37:15"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1968-08-27" firstname="Steffen"
				lastname="Cousteau" idemployee="s.cousteau" phone="703757079">
				<homeaddress box="" city="Holsbeek" country="Belgium"
					zip="3220" number="135" street="BurgemeesterdenOudenstraat" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2015-06-03T08:15:49" to="2015-07-16T07:08:26"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1990-01-25" firstname="Julia" lastname="Alblas"
				idemployee="j.alblas" phone="330950558">
				<homeaddress box="" city="Voeren" country="Belgium" zip="3790"
					number="152" street="Amsterdamseweg" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-05-22T08:50:05" to="2014-10-31T00:40:02"
						reason="autres" />
					<unavailability from="2014-02-18T08:20:50" to="2014-02-18T10:24:27"
						reason="panne" />
				</unavailabilities>
			</employee>
			<employee birthdate="1975-12-07" firstname="Niklas"
				lastname="van Stratum" idemployee="n.van stratum" phone="2013412520">
				<homeaddress box="C" city="Holsbeek" country="Belgium"
					zip="3220" number="240" street="Patijnstraat" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T11:47:32" to="2014-02-18T13:34:05"
						reason="panne" />
					<unavailability from="2014-09-10T09:27:17" to="2015-08-11T00:45:08"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1974-08-19" firstname="Timothée"
				lastname="Gravesteijn" idemployee="t.gravesteijn" phone="1500249857">
				<homeaddress box="D" city="Ottergem" country="Belgium"
					zip="9420" number="8" street="SlimmeWatering" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-12-02T17:18:16" to="2015-07-06T22:07:02"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1948-10-22" firstname="Bernadette"
				lastname="Sharma" idemployee="b.sharma" phone="1190791206">
				<homeaddress box="" city="Battice" country="Belgium"
					zip="4651" number="40" street="Rue Roussy" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T11:02:23" to="2014-02-18T14:44:26"
						reason="panne" />
					<unavailability from="2014-02-24T06:16:25" to="2014-02-26T05:49:09"
						reason="assigné" assignedcenter="Mons" />
				</unavailabilities>
			</employee>
			<employee birthdate="1943-08-20" firstname="Legget"
				lastname="Adams" idemployee="l.adams" phone="2045282781">
				<homeaddress box="" city="Cherain" country="Belgium"
					zip="6673" number="43" street="Rue Frédéric Chopin" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2015-01-24T19:38:45" to="2015-06-18T19:06:41"
						reason="congé" />
					<unavailability from="2014-02-18T16:13:33" to="2014-02-18T17:51:33"
						reason="panne" />
				</unavailabilities>
			</employee>
		</employees>
		<trolleys>
			<trolley status="empty">
				<dimension totalheight="0.8982626" usefulheight="0.7485522"
					usefullength="1.8366225" usefulwidth="1.6858656" volume="2.3177414" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="0.93610066" usefulheight="0.7800839"
					usefullength="2.1350813" usefulwidth="0.8438744" volume="1.4055086" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="0.59836704" usefulheight="0.4986392"
					usefullength="1.6083739" usefulwidth="1.505928" volume="1.2077516" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="0.67476517" usefulheight="0.5623043"
					usefullength="1.4348559" usefulwidth="0.9057488" volume="0.7307814" />
			</trolley>
			<trolley status="empty">
				<dimension totalheight="1.0102575" usefulheight="0.8418812"
					usefullength="1.8696194" usefulwidth="0.8653935" volume="1.3621272" />
			</trolley>
			<trolley status="ready-deliver">
				<dimension totalheight="0.778608" usefulheight="0.64884"
					usefullength="1.8476849" usefulwidth="1.1218725" volume="1.3449589" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="0.9891868" usefulheight="0.82432234"
					usefullength="1.2025938" usefulwidth="1.136188" volume="1.1263316" />
			</trolley>
			<trolley status="ready-deliver">
				<dimension totalheight="1.2361407" usefulheight="1.0301173"
					usefullength="1.9495697" usefulwidth="1.1571538" volume="2.3238952" />
			</trolley>
			<trolley status="empty">
				<dimension totalheight="0.53464705" usefulheight="0.4455392"
					usefullength="1.6224216" usefulwidth="1.2013401" volume="0.86839163" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="1.2229679" usefulheight="1.0191399"
					usefullength="1.5628057" usefulwidth="0.7378087" volume="1.1751208" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="1.2252231" usefulheight="1.0210192"
					usefullength="2.1723514" usefulwidth="1.529822" volume="3.3931644" />
			</trolley>
		</trolleys>
		<vehicles>
			<vehicle model="Opel vivano" passengernumber="2"
				usefulweight="712.2704">
				<dimension totalheight="1.6636506" usefulheight="1.3863755"
					usefullength="2.2988956" usefulwidth="1.0851423" volume="3.4584923" />
				<employeeincharge>k.bisaillon</employeeincharge>
			</vehicle>
			<vehicle model="Opel vivano" passengernumber="2"
				usefulweight="1000.4353">
				<dimension totalheight="2.4167774" usefulheight="2.013981"
					usefullength="2.0780864" usefulwidth="1.6103756" volume="6.7397876" />
				<employeeincharge>m.desnoyer</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n14" passengernumber="1"
				usefulweight="560.8518">
				<dimension totalheight="2.425549" usefulheight="2.0212908"
					usefullength="2.6650238" usefulwidth="1.8912755" volume="10.187901" />
				<employeeincharge>m.salmons</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n14" passengernumber="2"
				usefulweight="771.4289">
				<dimension totalheight="2.063745" usefulheight="1.7197875"
					usefullength="2.2019231" usefulwidth="1.6263769" volume="6.1588287" />
				<employeeincharge>s.cousteau</employeeincharge>
			</vehicle>
			<vehicle model="Opel vivano" passengernumber="1"
				usefulweight="982.6043">
				<dimension totalheight="1.9227078" usefulheight="1.6022565"
					usefullength="1.9465216" usefulwidth="1.6898718" volume="5.270418" />
				<employeeincharge>j.alblas</employeeincharge>
			</vehicle>
			<vehicle model="Citroën Nemo" passengernumber="2"
				usefulweight="747.1399">
				<dimension totalheight="2.3250911" usefulheight="1.9375759"
					usefullength="2.0092385" usefulwidth="1.1873205" volume="4.6223006" />
				<employeeincharge>n.van stratum</employeeincharge>
			</vehicle>
			<vehicle model="Ford transit connect" passengernumber="2"
				usefulweight="845.2787">
				<dimension totalheight="2.2326217" usefulheight="1.8605181"
					usefullength="2.3533947" usefulwidth="1.4663057" volume="6.4202685" />
				<employeeincharge>t.gravesteijn</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n14" passengernumber="1"
				usefulweight="958.0739">
				<dimension totalheight="2.0907466" usefulheight="1.7422888"
					usefullength="2.4690955" usefulwidth="1.1865373" volume="5.104338" />
				<employeeincharge>b.sharma</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n14" passengernumber="2"
				usefulweight="834.5094">
				<dimension totalheight="2.184692" usefulheight="1.8205765"
					usefullength="2.0939472" usefulwidth="1.9226841" volume="7.329639" />
				<employeeincharge>l.adams</employeeincharge>
			</vehicle>
		</vehicles>
	</center>
</centers>

=== laurentkeil/lil-g3r/DC2.xml
<?xml version="1.0" encoding="UTF-8"?>
<centers xmlns="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hlbexpress.com/namespaces/HLB-dispatching-centers ../HLB-DC.xsd ">
	<center name="Hasselt">
		<employees>
			<employee birthdate="1915-05-07" firstname="Romijn"
				lastname="Dukker" idemployee="r.dukker" phone="479713620">
				<homeaddress box="C" city="Sint-Stevens-Woluwe" country="Belgium"
					zip="1932" number="140" street="Rue Adolphe Wurtz" />
				<role>préposé</role>
			</employee>
			<employee birthdate="1962-01-08" firstname="Helmer"
				lastname="Grivois" idemployee="h.grivois" phone="733471720">
				<homeaddress box="B" city="Genk" country="Belgium" zip="3600"
					number="186" street="AlbrechtRodenbachstraat" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-08-06T13:14:57" to="2015-01-09T02:47:47"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1930-04-07" firstname="Talbot"
				lastname="Desnoyers" idemployee="t.desnoyers" phone="1698248781">
				<homeaddress box="C" city="Mont-Sainte-Geneviève"
					country="Belgium" zip="6540" number="125" street="Boulevard Aristide Briand" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T13:47:17" to="2014-02-18T13:51:10"
						reason="ciruclation" />
				</unavailabilities>
			</employee>
			<employee birthdate="1914-06-21" firstname="Royale"
				lastname="Garcia" idemployee="r.garcia" phone="65525013">
				<homeaddress box="" city="Floreffe" country="Belgium"
					zip="5150" number="244" street="Avenue de l'Amandier" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-20T08:44:41" to="2014-02-27T21:04:22"
						reason="assigné" assignedcenter="Hasselt" />
				</unavailabilities>
			</employee>
			<employee birthdate="1991-12-07" firstname="Lorraine"
				lastname="Monjeau" idemployee="l.monjeau" phone="2084649081">
				<homeaddress box="C" city="Rumsdorp" country="Belgium"
					zip="3400" number="73" street="Corduwenerstraat" />
				<role>coursier</role>
			</employee>
			<employee birthdate="1927-01-02" firstname="Ralf" lastname="Bordeaux"
				idemployee="r.bordeaux" phone="1965535510">
				<homeaddress box="" city="Kessel" country="Belgium" zip="2560"
					number="225" street="JonkersvanOssstraat" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T11:13:58" to="2014-02-18T11:15:06"
						reason="ciruclation" />
				</unavailabilities>
			</employee>
			<employee birthdate="1983-12-22" firstname="Katharina"
				lastname="Des Meaux" idemployee="k.des meaux" phone="247359051">
				<homeaddress box="" city="Vielsalm" country="Belgium"
					zip="6690" number="26" street="Rue Gustave Eiffel" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-18T09:31:20" to="2014-02-18T17:58:48"
						reason="panne" />
					<unavailability from="2014-02-18T14:56:03" to="2014-02-18T16:37:15"
						reason="panne" />
					<unavailability from="2015-05-20T17:48:57" to="2015-09-17T21:39:39"
						reason="congé" />
				</unavailabilities>
			</employee>
			<employee birthdate="1940-06-28" firstname="Dixie" lastname="Mailly"
				idemployee="d.mailly" phone="1922346419">
				<homeaddress box="B" city="Vezon" country="Belgium" zip="7538"
					number="138" street="Avenue De Marlioz" />
				<role>coursier</role>
				<unavailabilities>
					<unavailability from="2014-02-20T00:33:24" to="2014-02-28T19:13:27"
						reason="assigné" assignedcenter="Hasselt" />
					<unavailability from="2014-02-18T11:28:26" to="2014-02-18T12:37:34"
						reason="ciruclation" />
				</unavailabilities>
			</employee>
		</employees>
		<trolleys>
			<trolley status="outgoing">
				<dimension totalheight="0.795173" usefulheight="0.66264415"
					usefullength="1.8849692" usefulwidth="1.2447593" volume="1.5547838" />
			</trolley>
			<trolley status="ready-deliver">
				<dimension totalheight="1.3415676" usefulheight="1.1179731"
					usefullength="2.0829043" usefulwidth="1.3286222" volume="3.0938709" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="0.992677" usefulheight="0.8272308"
					usefullength="1.3569529" usefulwidth="1.4937904" volume="1.6767995" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="1.1184317" usefulheight="0.9320264"
					usefullength="1.5406798" usefulwidth="0.7942951" volume="1.1405714" />
			</trolley>
			<trolley status="empty">
				<dimension totalheight="1.0625488" usefulheight="0.8854573"
					usefullength="1.2099532" usefulwidth="0.7469387" volume="0.80024165" />
			</trolley>
			<trolley status="ready-deliver">
				<dimension totalheight="1.2690649" usefulheight="1.0575541"
					usefullength="2.102056" usefulwidth="1.1117749" volume="2.4715178" />
			</trolley>
			<trolley status="incoming">
				<dimension totalheight="0.93706274" usefulheight="0.78088564"
					usefullength="1.6131539" usefulwidth="0.89880764" volume="1.1322179" />
			</trolley>
			<trolley status="outgoing">
				<dimension totalheight="0.8967879" usefulheight="0.7473232"
					usefullength="1.200793" usefulwidth="1.4773024" volume="1.3257024" />
			</trolley>
		</trolleys>
		<vehicles>
			<vehicle model="Ford transit connect" passengernumber="1"
				usefulweight="740.4757">
				<dimension totalheight="1.8039412" usefulheight="1.5032843"
					usefullength="2.8955662" usefulwidth="1.9850191" volume="8.64051" />
				<employeeincharge>r.dukker</employeeincharge>
			</vehicle>
			<vehicle model="Opel Movano" passengernumber="1"
				usefulweight="785.29785">
				<dimension totalheight="2.3526957" usefulheight="1.9605798"
					usefullength="2.4840696" usefulwidth="1.9179385" volume="9.3407755" />
				<employeeincharge>h.grivois</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n14" passengernumber="2"
				usefulweight="800.4685">
				<dimension totalheight="2.015417" usefulheight="1.6795143"
					usefullength="2.4103696" usefulwidth="1.1058736" volume="4.476853" />
				<employeeincharge>t.desnoyers</employeeincharge>
			</vehicle>
			<vehicle model="Ford transit connect" passengernumber="1"
				usefulweight="475.25708">
				<dimension totalheight="2.003664" usefulheight="1.66972"
					usefullength="2.7889774" usefulwidth="1.537612" volume="7.1603684" />
				<employeeincharge>r.garcia</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n14" passengernumber="1"
				usefulweight="638.09424">
				<dimension totalheight="1.6412921" usefulheight="1.3677434"
					usefullength="2.6373956" usefulwidth="1.3778694" volume="4.970361" />
				<employeeincharge>l.monjeau</employeeincharge>
			</vehicle>
			<vehicle model="Ford transit connect" passengernumber="2"
				usefulweight="621.3547">
				<dimension totalheight="1.8049951" usefulheight="1.5041625"
					usefullength="2.5656345" usefulwidth="1.0080376" volume="3.8901494" />
				<employeeincharge>r.bordeaux</employeeincharge>
			</vehicle>
			<vehicle model="renault-trafic-n14" passengernumber="1"
				usefulweight="643.754">
				<dimension totalheight="2.0650673" usefulheight="1.7208894"
					usefullength="2.5187387" usefulwidth="1.6256812" volume="7.0464673" />
				<employeeincharge>k.des meaux</employeeincharge>
			</vehicle>
			<vehicle model="Ford transit" passengernumber="1"
				usefulweight="520.5925">
				<dimension totalheight="2.422518" usefulheight="2.018765"
					usefullength="2.7375734" usefulwidth="1.5003119" volume="8.291499" />
				<employeeincharge>d.mailly</employeeincharge>
			</vehicle>
		</vehicles>
	</center>
</centers>
